### ISSUE TITLE
我使用npm run dev 运行代码的时候出现了以下的打包问题，请问可以怎么解决

### ISSUE THREAD

**Issue by coderlsh** [mcuking/vitesandbox-client#1]
我使用npm run dev 运行代码的时候出现了以下的打包问题，请问可以怎么解决
`
WARNING in ./node_modules/vite/dist/browser/index.js 1497:43-50
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./src/vite/index.js 1:0-10:14 90:22-37 100:12-31 108:12-31 205:15-32 208:15-23 211:8-20 212:17-28 217:8-26 245:28-44
 @ ./src/viteWorker.js 7:10-35
 @ ./src/main.js 10:23-12:6
`

**Comment by mcuking** [comment]
> 我使用npm run dev 运行代码的时候出现了以下的打包问题，请问可以怎么解决 `WARNING in ./node_modules/vite/dist/browser/index.js 1497:43-50 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted @ ./src/vite/index.js 1:0-10:14 90:22-37 100:12-31 108:12-31 205:15-32 208:15-23 211:8-20 212:17-28 217:8-26 245:28-44 @ ./src/viteWorker.js 7:10-35 @ ./src/main.js 10:23-12:6`

这些是警告，并没有影响功能，我刚刚在 webpack 配置里加了一些参数，去除了这些警告，代码已上传。
```js
module: {
    unknownContextCritical : false,
    exprContextCritical: false,
}
```

**Comment by coderlsh** [comment]
> > 我使用npm run dev 运行代码的时候出现了以下的打包问题，请问可以怎么解决 `WARNING in ./node_modules/vite/dist/browser/index.js 1497:43-50 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted @ ./src/vite/index.js 1:0-10:14 90:22-37 100:12-31 108:12-31 205:15-32 208:15-23 211:8-20 212:17-28 217:8-26 245:28-44 @ ./src/viteWorker.js 7:10-35 @ ./src/main.js 10:23-12:6`
> 
> 这些是警告，并没有影响功能，我刚刚在 webpack 配置里加了一些参数，去除了这些警告，代码已上传。
> 
> ```js
> module: {
>     unknownContextCritical : false,
>     exprContextCritical: false,
> }
> ```

好的，谢谢啦
